In [1]:
import matplotlib
import numpy as np
import pandas as pd
from numerapi import NumerAPI
import random
import sklearn
import matplotlib.pyplot as plt
from utils import save_model, load_model, neutralize, get_biggest_change_features, validation_metrics, download_data
%matplotlib inline

from sklearn import (
    feature_extraction, feature_selection, decomposition, linear_model,
    model_selection, metrics, svm
)


In [27]:
train_data = pd.read_parquet('numerai_training_data.parquet')


NameError: name 'era' is not defined

In [29]:
train_data['era'] = train_data['era'].astype(int)
train_data.shape

(2412105, 1073)

In [30]:
#what features are available
features = [c for c in train_data if c.startswith('feature')]
print(features[:5])
targets = [c for c in train_data if c.startswith('target')]
target = 'target'
print(targets[:5])

['feature_dichasial_hammier_spawner', 'feature_rheumy_epistemic_prancer', 'feature_pert_performative_hormuz', 'feature_hillier_unpitied_theobromine', 'feature_perigean_bewitching_thruster']
['target', 'target_nomi_20', 'target_nomi_60', 'target_jerome_20', 'target_jerome_60']


In [46]:
sub_sampl_td = train_data[train_data.era.isin([i for i in range(1, 574, 8)])]
sub_sampl_td.shape

(301247, 1073)

In [49]:
sub2 = train_data[train_data.era.isin(range(3, 574, 8))]
sub3 = train_data[train_data.era.isin(range(5, 574, 8))]
sub4 = train_data[train_data.era.isin(range(7, 574, 8))]

In [59]:
X = sub_sampl_td[features]
y = sub_sampl_td[target]

In [66]:
model = linear_model.LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
model2 = linear_model.LinearRegression()
model2.fit(sub2[features], sub2[target])
model2.fit(sub3[features], sub3[target])
model2.fit(sub4[features], sub4[target])

y_pred = model2.predict(sub_sampl_td[features])
y_actual = sub_sampl_td[target]


In [72]:
rand = np.random.rand(len(y_actual))
np.corrcoef([y_pred, y_actual, rand])

array([[1.00000000e+00, 5.34140007e-02, 5.94429802e-04],
       [5.34140007e-02, 1.00000000e+00, 7.65295876e-04],
       [5.94429802e-04, 7.65295876e-04, 1.00000000e+00]])

In [68]:
y_pred = model.predict(sub2[features])
y_actual = sub2[target]

In [69]:
rand = np.random.rand(len(y_actual))

In [70]:
np.corrcoef([y_pred, y_actual, sub2[features].iloc[:,1], rand])

array([[ 1.        ,  0.05530899,  0.00794163,  0.00156338],
       [ 0.05530899,  1.        , -0.00153283,  0.00168634],
       [ 0.00794163, -0.00153283,  1.        ,  0.00185062],
       [ 0.00156338,  0.00168634,  0.00185062,  1.        ]])

In [65]:
np.corrcoef(y, X.iloc[:, 1])

array([[1.00000000e+00, 9.00049793e-04],
       [9.00049793e-04, 1.00000000e+00]])

## Preditions on tournament data

In [150]:
# tour_data = pd.read_parquet('numerai_tournament_data.parquet')
napi = NumerAPI()
napi.download_dataset('numerai_tournament_data.parquet', 'numerai_tournament_data.parquet')
tour_data = pd.read_parquet('numerai_tournament_data.parquet')
y_tour_pred = model2.predict(tour_data[features])

2022-02-27 16:43:32,883 INFO numerapi.utils: target file already exists
2022-02-27 16:43:32,922 INFO numerapi.utils: download complete


In [151]:
tour_data.head()

era data_type  feature_dichasial_hammier_spawner  \
id                                                                    
n000101811a8a843  0575      test                               0.50   
n001e1318d5072ac  0575      test                               0.25   
n002a9c5ab785cbb  0575      test                               0.25   
n002ccf6d0e8c5ad  0575      test                               0.50   
n0051ab821295c29  0575      test                               0.50   

                  feature_rheumy_epistemic_prancer  \
id                                                   
n000101811a8a843                               0.0   
n001e1318d5072ac                               1.0   
n002a9c5ab785cbb                               0.5   
n002ccf6d0e8c5ad                               1.0   
n0051ab821295c29                               0.0   

                  feature_pert_performative_hormuz  \
id                                                   
n000101811a8a843                               1.0   
n001e1318d5072ac                               0.5   
n002a9c5ab785cbb                               0.5   
n002ccf6d0e8c5ad                               0.5   
n0051ab821295c29                               0.0   

                  feature_hillier_unpitied_theobromine  \
id                                                       
n000101811a8a843                                  0.00   
n001e1318d5072ac                                  0.50   
n002a9c5ab785cbb                                  0.75   
n002ccf6d0e8c5ad                                  1.00   
n0051ab821295c29                                  0.25   

                  feature_perigean_bewitching_thruster  \
id                                                       
n000101811a8a843                                  0.75   
n001e1318d5072ac                                  0.25   
n002a9c5ab785cbb                                  0.25   
n002ccf6d0e8c5ad                                  0.50   
n0051ab821295c29                                  0.00   

                  feature_renegade_undomestic_milord  \
id                                                     
n000101811a8a843                                0.00   
n001e1318d5072ac                                0.75   
n002a9c5ab785cbb                                0.25   
n002ccf6d0e8c5ad                                1.00   
n0051ab821295c29                                1.00   

                  feature_koranic_rude_corf  \
id                                            
n000101811a8a843                       1.00   
n001e1318d5072ac                       0.75   
n002a9c5ab785cbb                       0.75   
n002ccf6d0e8c5ad                       0.75   
n0051ab821295c29                       0.50   

                  feature_demisable_expiring_millepede  ...  target_paul_20  \
id                                                      ...                   
n000101811a8a843                                  0.25  ...             NaN   
n001e1318d5072ac                                  0.00  ...             NaN   
n002a9c5ab785cbb                                  0.00  ...             NaN   
n002ccf6d0e8c5ad                                  0.50  ...             NaN   
n0051ab821295c29                                  0.25  ...             NaN   

                  target_paul_60  target_george_20  target_george_60  \
id                                                                     
n000101811a8a843             NaN               NaN               NaN   
n001e1318d5072ac             NaN               NaN               NaN   
n002a9c5ab785cbb             NaN               NaN               NaN   
n002ccf6d0e8c5ad             NaN               NaN               NaN   
n0051ab821295c29             NaN               NaN               NaN   

                  target_william_20  target_william_60  target_arthur_20  \
id                                                                         
n000101811a8a84

In [157]:
pred_df = tour_data["id"].to_frame()
pred_df['prediction'] = y_tour_pred
pred_df.head()
pred_df.to_csv('pred.csv', index=False)

KeyError: 'id'

In [156]:
pred_df.head()

id  prediction
id                                            
n000101811a8a843  n000101811a8a843    0.493799
n001e1318d5072ac  n001e1318d5072ac    0.534890
n002a9c5ab785cbb  n002a9c5ab785cbb    0.496155
n002ccf6d0e8c5ad  n002ccf6d0e8c5ad    0.497578
n0051ab821295c29  n0051ab821295c29    0.508729

In [159]:
# Get your API keys and model_id from https://numer.ai/notebook
public_id = "LQKTEJFA2UZ4ERFNSXVUNJUEDWZEXPYI"
secret_key = "KKMAFRZSIRYWKDLOJ6VLGJYLIPNKKYHVY7ALMVK37CH52II5JC7LIHAAE4VCI5PV"
model_id = "d537b445-b274-43b6-8687-a276f182ed33"
napi = NumerAPI(public_id=public_id, secret_key=secret_key)

In [164]:
# Upload your predictions
submission_id = napi.upload_predictions("pred.csv", model_id=model_id, version=2)

2022-02-27 17:28:11,368 INFO numerapi.base_api: uploading predictions...


In [161]:
help(napi.upload_predictions)

Help on method upload_predictions in module numerapi.numerapi:

upload_predictions(file_path: str = 'predictions.csv', tournament: int = 8, model_id: str = None, df: pandas.core.frame.DataFrame = None, version: int = 1) -> str method of numerapi.numerapi.NumerAPI instance
    Upload predictions from file.
    Will read TRIGGER_ID from the environment if this model is enabled with
    a Numerai Compute cluster setup by Numerai CLI.
    
    Args:
        file_path (str): CSV file with predictions that will get uploaded
        tournament (int): ID of the tournament (optional, defaults to 8)
            -- DEPRECATED there is only one tournament nowadays
        model_id (str): Target model UUID (required for accounts with
            multiple models)
        df (pandas.DataFrame): pandas DataFrame to upload, if function is
            given df and file_path, df will be uploaded.
        version (int): Version of create_submissions to use (optional,
            defaults to 1)
           

## Predictions on Validation data

In [158]:
val_data = pd.read_parquet('numerai_validation_data.parquet')
y_val_pred = model2.predict(val_data[features])

pred_df = val_data.index.to_frame()
pred_df['prediction'] = y_val_pred
pred_df.head()
pred_df.to_csv('pred_val.csv', index=False)



In [155]:
pred_df.head()

id  prediction
id                                            
n000101811a8a843  n000101811a8a843    0.493799
n001e1318d5072ac  n001e1318d5072ac    0.534890
n002a9c5ab785cbb  n002a9c5ab785cbb    0.496155
n002ccf6d0e8c5ad  n002ccf6d0e8c5ad    0.497578
n0051ab821295c29  n0051ab821295c29    0.508729

## Exploring data

In [118]:
def max_con(b,c):
    return np.corrcoef(b,c)[0,1]
#     con = 0
#     m = 0
#     for j in range(len(b)):
#         if b[j]!=c[j]:
#             con=0
#         else:
#             con+=1
#         if con>m:
#             m=con
#     return m

In [136]:
l1 = len(sub2[target])
l2 = len(sub3[target])
# i=0
a = np.array(
            [
                max_con(sub2[target].iloc[i:].values, sub3[target].iloc[:l1-i].values) 
                for i in range(0, int(l1/2), int(l1/100))
            ]
            )


In [139]:
np.corrcoef(sub2[target], sub3[target].iloc[:l1])

array([[1.00000000e+00, 1.65365753e-05],
       [1.65365753e-05, 1.00000000e+00]])

In [108]:
i = 0
b = sub2[target].iloc[i:].values
c = sub3[target].iloc[:l1-i].values


11
